### ISSUE TITLE
CreateItem & UpdateItem Firing "Max call stack size exceeded"

### ISSUE THREAD

**Issue by FiveOneDigital** [nmarus/node-ews#1]
First off - great module!  I was able to tweak it to get a lot of functions working with EWS correctly (including `FindItem`, `GetItem`, `Subscribe`, `GetEvents`, `ResolveNames`, and also `Impersonation` ).  It only took some minor tweaks to the code, but for the most part the xml2js & node-soap/wsdl.js handle the functions perfectly.  That is until CreateItem (or UpdateItem).  For some reason the following error fires:

>   if (Array.isArray(parameterTypeObj.$lookupTypes) && parameterTypeObj.$lookupTypes.length) {
>               ^
>   
>   RangeError: Maximum call stack size exceeded
>       at Function.isArray (native)
>       at WSDL.findChildSchemaObject (/../server/node-ews-rv/node-soap/lib/wsdl.js:1822:12)
>       at WSDL.findChildSchemaObject (/../server/node-ews-rv/node-soap/lib/wsdl.js:1862:20)

I can't for the life of me figure out what about these functions causes the error. I know the call stack exceeding has to do with (most likely) recursive functions, and .findChildSchemaObject does fire within itself in WSDL.js, but this has no effect on any other EWS operations but CreateItem & UpdateItem.

Any thoughts?

**Comment by nmarus** [comment]
Thanks for the details. Let me see if I can replicate it. The node-soap project is several revisions ahead of the fork I used that was modified for NTLM of which I also had to apply several updates to.

**Comment by FiveOneDigital** [comment]
Yeah I knew you had to use a fork and modify it for NTLM, which makes sense. I also took your module and removed all the tmp file creation (since my project is for internal use, I just directly downloaded the .wsdl files and added them to increase speed).  In any event, it's strange for everything to run and fire correctly except `CreateItem`.  Something is happening when looping through the ewsArgs for this function.

Thanks for looking into this though!  With this figured out, your module is light years ahead of any other node/ews integration.

**Comment by FiveOneDigital** [comment]
FYI: I just fixed this issue. I did so by using node-soap's `$xml` to manually set all the "children" of `CreateItem` with a string.  Obviously it'd be better if we could just use the JSON args object, but for some reason the children throw that Max call error.

**Comment by nmarus** [comment]
Excellent. I haven't had a chance to test your case yet, but I have finally removed that crazy dependency on that fork of a fork nonsense. :)  

It's using the the official node-soap library now (0.13.0) which has reduced the code base significantly. It still needs a lot of work, and I hope to get around to that soon. In the meantime, it should be easier to hack through. Also, noticed when looking through diffs that the current node-soap version has made several fixes around recursive functions, so here is hoping that was what was causing your issues.  

I'd appreciate any feedback if that fixed your particular case. If it didn't, would you mind sending me a sample sanitized query that is failing? My email is nmarus@gmail.com if you rather not post it here.

**Comment by hacker** [comment]
Hey, been there. I didn't resolve it (other than using literal xml), but I believe it's node-soap's WSDL parser chokes on exchange's wsdl once it sees CalendarItem…

**Comment by ervinfetic** [comment]
Hi, are there any updates on this issue. I am trying to send a CreateItem request but it fires the same error as the OP reported. @FiveOneDigital said that he was able to fix it but I do not understand what he means by "manually setting children of createitem with a string". I tracked the issue down to a recursive function when forming the request. It points to me that the request might be invalid, can you take a look at the following few lines of code and let me know if it seems ok.

This is enclosed in the body of the request operation of CreateItem:

<img width="248" alt="screen shot 2016-06-17 at 11 08 55" src="https://cloud.githubusercontent.com/assets/15788855/16145977/f8a08170-347b-11e6-932d-b891f8897683.png">

**Comment by xkmire** [comment]
Hi,
Had the same problem and dug into it a bit. I have a workaround here that is not very elegant but for me it works. The problem I had was that when findChildSchemaObject comes to object with 
  "$type": "t:ItemType",
  "$targetNamespace": "http://schemas.microsoft.com/exchange/services/2006/types"
it loads a schema that down the road contains another same item
  "$type": "t:ItemType",
  "$targetNamespace": "http://schemas.microsoft.com/exchange/services/2006/types"
and this goes on recursively forever.... and finally crash.

Patch that stops entering that schema if we are already inside this schema:
diff old/wsdl.js new/wsdl.js
1646c1646
<             var childSchemaObject = self.findChildSchemaObject(schemaObject, name);
---
>             var childSchemaObject = self.findChildSchemaObject(schemaObject, name, 0);
1746c1746,1747
<                 obj[self.options.attributesKey].xsi_type.xmlns);
---
>                 obj[self.options.attributesKey].xsi_type.xmlns,
>                 0);
1838c1839
< WSDL.prototype.findChildSchemaObject = function(parameterTypeObj, childName) {
---
> WSDL.prototype.findChildSchemaObject = function(parameterTypeObj, childName, insideSchemaMS) {
1879,1881c1880,1887
<     var typeDef = this.findSchemaType(typeInfo.name, childNsURI);
<     if (typeDef) {
<       return this.findChildSchemaObject(typeDef, childName);
---
>     if ((childNsURI.match("http://schemas.microsoft.com") == null) || (insideSchemaMS == 0)) {
>       var typeDef = this.findSchemaType(typeInfo.name, childNsURI);
>       if (typeDef) {
>         if (childNsURI.match("http://schemas.microsoft.com") != null)
>           return this.findChildSchemaObject(typeDef, childName, 1);
>         else
>           return this.findChildSchemaObject(typeDef, childName, 0);
>       }
1887c1893
<       found = this.findChildSchemaObject(child, childName);
---
>       found = this.findChildSchemaObject(child, childName, insideSchemaMS);
1900c1906
<           found = this.findChildSchemaObject(foundBase, childName);
---
>           found = this.findChildSchemaObject(foundBase, childName, insideSchemaMS);
1910d1915
<

**Comment by xkmire** [comment]
Wow. Those tags in the patch turned out horrible in that comment. Maybe it is possible to read anyway?

**Comment by fdamken** [comment]
You may want to use [this simple script](https://gist.github.com/fdamken/cf55eb86720f8fc525bd6a1d87c70f3b) to convert a JavaScript object into the required XML structure.

**Note: You need at least NodeJS 5 to run the script successfully.**

*Disclaimer: I wrote this script in a short time and it is not tested very well.*

**Comment by MMRandy** [comment]
Although @xkmire's post needs a little clean up, the changes did in fact work for me.  Any thoughts on making a PR out of this and getting it into the code base?

**Comment by nmarus** [comment]
Please try the 2.0.0-dev branch and see if that resolves issues. Note this is a major rewrite and some command syntax is different.

**Comment by patterncoder** [comment]
@xkmire implemented your changes in wsdl.js and it did the trick...yes that was hard to read but got 'er done...thanks

@nmarus also was under the gun timewise and had a failed attempt at 2.0.0 dev branch...was getting.... unable to verify the first certificate logged to the console...guessing our installation of ews is a little out of the norm?  Thanks for your work on this project...it was very helpful!

**Comment by facundoolano** [comment]
I'm also facing the max call stack size error, and not sure how to avoid it. 

The 2.0.0-dev branch doesn't seem to work, I'm getting the `Error: unable to verify the first certificate`  that @patterncoder mentioned.

**Comment by nmarus** [comment]
The original issue has been repaired with the version 2.0.0 code base. If you are still experiencing problems, please open a new issue. If there are issues that are still existing in this thread, please open a new issue for those.

**Comment by ervinfetic** [comment]
@facundoolano If you are using Nodejs just add this line below, it will solve your issue:

`process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";`

**Comment by facundoolano** [comment]
@ervinfetic thanks, but if you see #15 I get a different error when I use that patch.

**Comment by besla** [comment]
I get exactly same error. "unable to verify the first certificate" But when I use patch then I get "NTLM StatusCode 401: Unauthorized."
